import type { Lesson } from './lessons';
/** Beginner learning is grounded in the actual office tools, rather than invented AI capabilities. */
export const LEARNING: Lesson[] = [
  { id: 'study-hall', icon: '🎓', title: 'Classroom, study library and homework', words: 'class classroom study hall teacher professor curriculum lecture lesson test homework backpack highlight notes learning',
    what: 'The Classroom & study hall is its own elevator floor, with desks, Professor Ellis, a whiteboard and a separate subject library.',
    why: 'You can keep learning material, notes and homework together without putting them in GitHub.',
    steps: ['Take the elevator to Classroom & study hall. Use E at a desk or open Class & study tools.', 'Add reading material by subject in the library. Sit and read with notes, and select text to highlight passages.', 'Raise your hand for guided help. Homework can stay in your backpack or your break-floor locker.'],
    term: 'The teacher presents saved lesson material and learning guidance. Curriculum content, automatic grading and an AI tutor will be added separately.' },
  { id: 'git-start', icon: '🐙', title: 'Learn GitHub: what it is and why it helps', words: 'learn github git beginner explain understand tutorial utilise use online coding',
    what: 'GitHub is an online home for project files, their history, and conversations about changes. Think of it as a shared project cabinet with a record of who changed what.',
    why: 'Your workers can build a project locally and propose their work on GitHub, where you can review it before accepting it.',
    steps: ['Start with one project, called a repository or repo.', 'Ask a worker for one small change and a plain-English explanation.', 'Try the result. Ask for corrections, then review the pull request before merging it.'],
    example: 'Teach me how this project uses GitHub. Show me the files, explain what you plan to change, and tell me how I can test it.', term: 'Git records the history. GitHub is a service that keeps an online copy and helps people collaborate.' },
  { id: 'git-save', icon: '💾', title: 'Saving, committing, pushing, and pulling', words: 'save commit checkpoint push pull sync upload download github history undo backup',
    what: 'Saving edits a file on this computer. A commit records a checkpoint. Pushing sends recorded commits to GitHub. Pulling brings remote changes back down.',
    why: 'These are separate steps. Work may be on your laptop before it has been recorded or sent online.',
    steps: ['Ask the worker what files it edited and how it tested them.', 'Ask it to commit the changes when they are ready to record.', 'Ask it to push its branch and open a pull request. Review what will be shared.'],
    example: 'Is this saved only on my computer, or is it on GitHub too? Explain the current state before you push anything.', term: 'A commit is a history checkpoint. Uploaded books and drawings in your break floor are saved locally outside Git.' },
  { id: 'git-branches', icon: '🌿', title: 'Branches and worktrees: room to try a change', words: 'branch worktree isolated experiment parallel separate worker conflict main fork',
    what: 'A branch is another line of project history. A worktree gives that branch its own working folder, so two workers can work in separate folders.',
    why: 'Separate worktrees help workers avoid overwriting one another while you compare their proposals.',
    steps: ['When hiring a worker for a task, choose its own git worktree when available.', 'Keep each task focused, especially when several workers edit the same project.', 'Let a worker resolve conflicts and explain the combined result if two proposals overlap.'],
    example: 'Work in your own branch and worktree. Open a pull request and explain how your changes affect the other workers’ work.', term: 'Main usually means the project’s primary branch. A fork is your own GitHub copy of another repository.' },
  { id: 'git-review', icon: '✅', title: 'Review a worker’s work before accepting it', words: 'review approve accept test check verify merge pr pull request changes diff wrong result',
    what: 'Review means checking whether the result does what you asked. You can do that even while learning to read code.',
    why: 'A confident worker can still make mistakes. Working buttons and a clear explanation are useful evidence.',
    steps: ['Ask for a summary of what changed and why.', 'Open its preview and try the main actions yourself. Ask what checks passed and what could not be checked.', 'Read the pull request. Request changes if needed. Merge when you are satisfied.'],
    example: 'Explain this PR without coding jargon. Give me three things to click to check it, and list anything you have not verified.', term: 'A diff shows changed text. A pull request is the proposed change; merging accepts it into its target branch.' },
  { id: 'git-publish', icon: '🚀', title: 'Putting work online or publishing a game', words: 'publish deploy steam release website online internet finished executable game hosting',
    what: 'Putting code on GitHub records and shares development work. Publishing makes a usable website or installable game available to its audience.',
    why: 'You may need a website host or a packaged game build even after the changes are merged.',
    steps: ['Ask for a local preview first.', 'For a website, choose hosting and have the worker explain the deployment step.', 'For a Steam game, build and test a standalone version, then prepare the Steamworks release separately.'],
    example: 'The code is on GitHub. What else is needed for someone to use the finished app? Explain the options and costs before publishing.', term: 'Deployment means placing a working version where people can run it.' },
  { id: 'git-workers', icon: '🧑‍🏫', title: 'How to direct a worker when you are unsure', words: 'worker help confused unsure prompt request teach learn coding programming explain plan mistakes instructions',
    what: 'Tell a worker the outcome you want, what is happening now, and what would count as success. You can ask it to teach you along the way.',
    why: 'A clear goal is useful even if you do not know the programming words.',
    steps: ['Give one small task with an example of the desired result.', 'Ask it to explain its plan and any important choices.', 'Request a preview and a simple checklist to verify the result. Give feedback using what you see.'],
    example: 'I’m learning. Make a contact form with name, email, and message. Explain each major step in ordinary language, then show me how to test it.', term: 'Pip’s answers come from this built-in office guide. A coding worker can investigate your actual project and explain its files.' },
  { id: 'break-floor', icon: '🌿', title: 'The shared break floor', words: 'break floor cafeteria kitchen food coffee burger hotdog meal barista chef order volunteer minigame rush',
    what: 'The break floor is a shared facility, available without creating a GitHub repository. Mae takes orders and makes coffee; Gus cooks the hot food.',
    why: 'You can eat, read, draw, organize files, or volunteer for a kitchen shift while taking a break.',
    steps: ['Choose Break floor in the elevator, alongside your project floors and rooftop bar.', 'Walk around with the usual office controls and press E at a station, or use Floor guide to walk there.', 'Order food and collect it when ready. The volunteer station lets you play barista or chef in Breakroom Rush.'], term: 'The break floor is a shared building destination. Its records and uploads save to the office server’s local data folder outside GitHub.' },
  { id: 'library', icon: '📚', title: 'Upload books and read on the couch', words: 'book books library pdf epub reading read pages page flip bookmark couch lounge upload',
    what: 'The library accepts your PDF, EPUB, TXT, and Markdown books. PDFs keep their original pages; EPUB and text are arranged into reading pages.',
    why: 'You can keep books in the office without adding them to GitHub.',
    steps: ['Visit the break floor’s library and choose a file to upload.', 'Choose Take book to couch. You will sit by the window and open the book.', 'Use Previous / Next, the page edges, or arrow keys. Closing the book saves your bookmark.'], term: 'Upload copies a file to this office’s local storage. Keep a separate backup of valuable books.' },
  { id: 'studio', icon: '🎨', title: 'Draw, save, and leave art on display', words: 'paint drawing art sketch brush shapes text canvas erase save undo png whiteboard desk',
    what: 'The drawing desk is a built-in drawing tool. Your drawing stays on display after you close it, like the office whiteboard.',
    why: 'You can sketch an idea and keep it beside your work without launching another app.',
    steps: ['Visit the drawing desk on the break floor.', 'Choose a brush, eraser, shape, or text. Changes save automatically; check the saved message.', 'Download PNG for a copy on your laptop, or Save PNG to art shelf before starting another canvas.'], term: 'PNG is an image file that many apps can open. Save now records your editable canvas locally.' },
  { id: 'organizer', icon: '🗂️', title: 'Documents, Canva, Google Docs, and mood boards', words: 'document docs google sheets canva design mood board file folder tag organize accounting upload external app',
    what: 'The document organizer holds local uploads and links to documents or designs in other apps. It can display image previews as a mood board.',
    why: 'Your non-coding work can have a home in the office too.',
    steps: ['Choose Documents & mood boards on the break floor.', 'Add a file or an https link, give it a name, and set a folder and tags.', 'Search your items, edit their details, or open the original app. Google and Canva account syncing requires a separate connection.'], term: 'A link points to the original file. Upload creates a separate local copy.' },
  { id: 'staff-storage', icon: '🧥', title: 'Staff, employee records, supplies, and lockers', words: 'clean cleaning lady june leon maintenance repairs stock bathroom supplies store room storeroom records reviews complaints personal coats locker',
    what: 'June cleans the office and break floor; Leon does maintenance rounds. The storeroom organizes employee records and supplies, and the lockers hold your personal lists and uploads.',
    why: 'These give the building everyday routines and somewhere to organize office information.',
    steps: ['Press E near June or Leon on a project floor to learn what they do.', 'Visit the storeroom for records, documents, or supplies inventory.', 'Use your locker to save personal items and files. Individual accounts have separate storage; shared-password visitors share a cabinet.'], term: 'These animated routines use no AI calls. The records cabinet has not been designed as a protected HR system.' },
];
