import * as THREE from 'three';
import { h,toast } from '../../ui/dom';
import { Studio } from '../facilities/studio';
import { Collection,upload,assetUrl,type Asset } from '../facilities/data';
import { panel,action,input,chooseFile } from './panels';
import { launch,post,webLink } from './files';
interface Board {id:string;name:string;cards:{asset:Asset;caption:string}[];}
interface Sketchbook {id:string;name:string;pages:Asset[];}
export class ArtStudio {
  readonly boards=new Collection<{active:number;items:Board[]}>('creative-boards',{active:0,items:[]});
  readonly books=new Collection<{items:Sketchbook[];wall:Asset[]}>('creative-books',{items:[],wall:[]});
  readonly drawing:Studio;
  constructor(private texture:(station:string,texture:THREE.Texture)=>void){this.drawing=new Studio(()=>this.texture('sketch',new THREE.CanvasTexture(this.drawing.canvas)),'creative-art');}
  async desk(){const p=panel('✏ Blackline art desk');p.body.append(action('Draw on the persistent sketch pad',()=>{p.modal.close();return this.drawing.open();}),action('Sketchbooks & finished sketches',()=>{p.modal.close();return this.sketchbooks();}),action('Multiple mood boards',()=>{p.modal.close();return this.moodboards();}),webLink('ChatGPT · generate or augment an image','https://chatgpt.com/'),h('p',{},'Bring images back from ChatGPT with Upload finished sketch. Open any saved image in Paint, save there, then import its edited copy.'),chooseFile('.png,.jpg,.jpeg,.webp',async file=>{const a=await upload(file);await this.drawing.data.load();this.drawing.data.value.gallery.unshift(a);await this.drawing.data.save();toast('Image added to your finished art shelf.');}));}
  async aiImage(){const p=panel('✨ Image generation & augmentation',true),prompt=input('Describe the image or changes','',true),status=h('p.studio-status',{},'Uses your configured OpenAI API connection. Only pressing Create sends your prompt and selected image.');let image:Asset|undefined;p.body.append(prompt.row,chooseFile('.png,.jpg,.jpeg,.webp',async file=>{image=await upload(file);status.textContent='Reference image: '+image.name;}),status,action('Create image / augment reference',async()=>{status.textContent='Creating your image…';const a=await post('/api/studios/image',{prompt:prompt.field.value,image:image?.id});await this.drawing.data.load();this.drawing.data.value.gallery.unshift(a);await this.drawing.data.save();p.body.append(h('img',{src:assetUrl(a),alt:'Generated image'}));status.textContent='Saved to your finished art shelf. Add it to a sketchbook, mood board or wall.';}));}
  async moodboards(){
    await this.boards.load();const p=panel('🖼 Multiple mood boards',true),space=h('div.studio-mood'),name=input('Mood board name'),count=h('strong');
    const active=()=>this.boards.value.items[this.boards.value.active];
    const render=()=>{const b=active();name.field.value=b?.name??'';count.textContent=b?`Board ${this.boards.value.active+1} of ${this.boards.value.items.length}`:'Create your first board';space.replaceChildren(...(b?.cards??[]).map((c,i)=>h('figure',{},h('img',{src:assetUrl(c.asset),alt:c.caption}),h('figcaption',{},c.caption),action('← Move earlier',async()=>{if(i>0){[b.cards[i-1],b.cards[i]]=[b.cards[i],b.cards[i-1]];await this.boards.save();render();}}),action('Remove card',async()=>{b.cards.splice(i,1);await this.boards.save();render();}))));void this.showBoard();};
    const turn=async(n:number)=>{if(!this.boards.value.items.length)return;this.boards.value.active=(this.boards.value.active+n+this.boards.value.items.length)%this.boards.value.items.length;await this.boards.save();render();};
    p.body.append(h('div.fac-toolbar',{},action('← Previous board',()=>turn(-1)),count,action('Next board →',()=>turn(1)),action('New mood board',async()=>{this.boards.value.items.push({id:crypto.randomUUID(),name:'New mood board',cards:[]});this.boards.value.active=this.boards.value.items.length-1;await this.boards.save();render();})),name.row,action('Rename board',async()=>{if(active()){active().name=name.field.value.slice(0,120);await this.boards.save();render();}}),chooseFile('.png,.jpg,.jpeg,.webp',async file=>{if(!active())throw new Error('Create a mood board first.');active().cards.push({asset:await upload(file),caption:file.name});await this.boards.save();render();}),space);render();
  }
  async showBoard(){const b=this.boards.value.items[this.boards.value.active],canvas=document.createElement('canvas');canvas.width=1000;canvas.height=600;const g=canvas.getContext('2d')!;g.fillStyle='#e8ddc2';g.fillRect(0,0,1000,600);g.fillStyle='#314e56';g.font='36px sans-serif';g.fillText(b?.name??'Mood boards · your inspiration',30,50);for(const [i,c] of (b?.cards??[]).slice(0,6).entries()){const image=new Image();image.src=assetUrl(c.asset);try{await image.decode();g.drawImage(image,30+i%3*325,90+Math.floor(i/3)*245,300,220);}catch{}}this.texture('moodboards',new THREE.CanvasTexture(canvas));}
  async sketchbooks(){
    await Promise.all([this.books.load(),this.drawing.load()]);const p=panel('📚 Sketchbooks & wall gallery',true),list=h('div.fac-grid'),select=h('select',{'aria-label':'Sketchbook'});
    const render=()=>{select.replaceChildren(...this.books.value.items.map(b=>h('option',{value:b.id},b.name)));list.replaceChildren(...this.drawing.data.value.gallery.map(a=>h('article.fac-card',{},h('img',{src:assetUrl(a),alt:a.name}),h('strong',{},a.name),h('a.btn',{href:assetUrl(a,true),download:a.name},'Download image'),action('Add to selected sketchbook',async()=>{const b=this.books.value.items.find(b=>b.id===select.value);if(!b)throw new Error('Create a sketchbook first.');b.pages.push(a);await this.books.save();toast('Added to '+b.name);}),action('Hang on wall',async()=>{this.books.value.wall.push(a);this.books.value.wall=this.books.value.wall.slice(-4);await this.books.save();await this.showWall();}),action('Open in Paint',()=>launch('paint',a)),action('Import saved Paint edits',async()=>{const edited=await post('/api/studios/import',{asset:a.id});this.drawing.data.value.gallery.unshift(edited);await this.drawing.data.save();render();}))));};
    const name=input('New sketchbook name','Finished sketches');p.body.append(name.row,action('Create sketchbook',async()=>{this.books.value.items.push({id:crypto.randomUUID(),name:name.field.value.slice(0,120),pages:[]});await this.books.save();render();}),select,action('Flip through selected sketchbook',()=>{const b=this.books.value.items.find(b=>b.id===select.value);if(!b||!b.pages.length)throw new Error('Add some finished sketches to this book first.');const book=panel('📖 '+b.name,true),image=h('img',{alt:b.name}),count=h('span');let page=0;const turn=(n:number)=>{page=Math.max(0,Math.min(b.pages.length-1,page+n));image.src=assetUrl(b.pages[page]);count.textContent=`Page ${page+1} of ${b.pages.length}`;};book.body.append(h('div.fac-toolbar',{},action('← Previous sketch',()=>turn(-1)),count,action('Next sketch →',()=>turn(1))),image);turn(0);}),chooseFile('.png,.jpg,.jpeg,.webp',async file=>{this.drawing.data.value.gallery.push(await upload(file));await this.drawing.data.save();render();}),list);render();
  }
  async showWall(){const canvas=document.createElement('canvas');canvas.width=1200;canvas.height=500;const g=canvas.getContext('2d')!;g.fillStyle='#f8f3e7';g.fillRect(0,0,1200,500);for(const [i,a]of this.books.value.wall.entries()){const image=new Image();image.src=assetUrl(a);try{await image.decode();g.drawImage(image,20+i*300,30,270,430);}catch{}}this.texture('sketchbooks',new THREE.CanvasTexture(canvas));}
}
