import { h,toast } from '../../ui/dom';
import { panel,action,input } from './panels';
import { request } from '../facilities/data';
import { post,webLink,launch } from './files';
export async function studioConnections(){
  const c=await request('/api/studios/connections'),p=panel('🔌 Studio connections',true),openai=input('OpenAI API key'),claude=input('Anthropic API key'),openaiModel=input('OpenAI design model','gpt-4.1'),claudeModel=input('Claude design model','claude-sonnet-4-5');
  for(const field of [openai.field,claude.field]){field.setAttribute('type','password');field.setAttribute('autocomplete','off');}
  p.body.append(h('p',{},'Connect your own API access for prompt-and-image design and image generation. Keys are encrypted in your personal office vault and are never sent back to the browser. A website subscription is separate from API billing. Requests run only when you press an AI creation button.'),h('p.studio-status',{},`OpenAI: ${c.ai.openai?'configured':'not configured'}\nClaude: ${c.ai.claude?'configured':'not configured'}\nFL Studio: ${c.apps.fl?'installed':'not found'} · Blender: ${c.apps.blender?'installed':'not found'} · Paint: ${c.apps.paint?'installed':'not found'}`),openai.row,claude.row,openaiModel.row,claudeModel.row,action('Save API connections',async()=>{await post('/api/studios/settings',{...(openai.field.value?{openai:openai.field.value}:{}),...(claude.field.value?{claude:claude.field.value}:{}),openaiModel:openaiModel.field.value,claudeModel:claudeModel.field.value});openai.field.value=claude.field.value='';toast('Connections saved.');p.modal.close();}),action('Remove saved API keys',async()=>{await post('/api/studios/settings',{openai:'',claude:''});toast('Saved keys removed. Server environment keys, if set, still apply.');p.modal.close();}),h('div.fac-toolbar',{},webLink('OpenAI API account','https://platform.openai.com/api-keys'),webLink('Anthropic API account','https://console.anthropic.com/'),webLink('BandLab','https://www.bandlab.com/'),webLink('SUNO','https://suno.com/'),action('Open FL Studio',()=>launch('fl')),action('Open Blender',()=>launch('blender')),action('Open Paint',()=>launch('paint'))));
}
