import * as THREE from 'three';
import { h,toast } from '../../ui/dom';
import { recipe,scad,svgPattern,DESIGN_INSTRUCTION,type Recipe,type Part } from '../../../shared/studio-files';
import { panel,action,input,chooseFile } from './panels';
import { upload,request,type Asset } from '../facilities/data';
import { ProjectFiles,post,download,launch,webLink } from './files';
import { loadModel,disposeModel,preview } from './models';
import type { StudioWorld } from './world';
export class CraftStudio {
  readonly files=new ProjectFiles();
  constructor(private world:()=>StudioWorld){}
  async display(station:string,asset:Asset,save=true){const model=await loadModel(asset),group=this.world().displays.get(station);if(!group)return;for(const child of [...group.children]){disposeModel(child);group.remove(child);}group.add(model);model.position.y=1;if(save){await this.files.data.load();for(const f of this.files.data.value)if(f.station===station)f.display=f.asset.id===asset.id;await this.files.data.save();toast('Prototype displayed at '+station+' station.');}}
  async restore(){await this.files.data.load();for(const f of this.files.data.value.filter(f=>f.display))await this.display(f.station,f.asset,false);}
  async open(station:string){
    const p=panel('🛠 '+station+' · design & prototype',true),connections=await request('/api/studios/connections'),shape=h('select',{'aria-label':'Prototype shape'});
    for(const s of ['box','ring','vase','assembly'])shape.append(h('option',{value:s},s));shape.value=station==='jewellery'?'ring':station==='sculpture'?'vase':'box';
    const fields=Object.fromEntries((['width','height','depth','wall']as const).map(k=>[k,input(k+' (millimetres)',String(k==='wall'?3:k==='height'?60:100))])) as Record<'width'|'height'|'depth'|'wall',ReturnType<typeof input>>;
    if(station==='jewellery'){fields.width.field.value='22';fields.height.field.value='5';fields.depth.field.value='22';fields.wall.field.value='2';}
    const color=h('input',{type:'color',value:'#a99b83','aria-label':'Material color'}),prompt=input('Describe what you want to make','',true),provider=h('select',{'aria-label':'AI design assistant'}),status=h('p.studio-status',{},'Build a measured prototype without learning Blender. Start with a box, ring or vase, then edit it in Blender when you want more detail.');
    provider.append(h('option',{value:'openai'},'ChatGPT / OpenAI'),h('option',{value:'claude'},'Claude'));let conceptImage:Asset|undefined,parts:Part[]|undefined;
    const get=()=>recipe({shape:shape.value,width:Number(fields.width.field.value),height:Number(fields.height.field.value),depth:Number(fields.depth.field.value),wall:Number(fields.wall.field.value),color:color.value,parts});
    const current=()=>{try{return JSON.stringify(get());}catch{return 'No validated design yet.';}};
    const put=(r:Recipe)=>{shape.value=r.shape;for(const k of ['width','height','depth','wall']as const)fields[k].field.value=String(r[k]);color.value=r.color;parts=r.parts;json.value=JSON.stringify(r,null,2);};
    const build=async()=>{const r=get();status.textContent='Blender is building your design…';try{const result=await post('/api/studios/prototype',{recipe:r});await this.files.data.load();for(const asset of result.assets)this.files.data.value.push({station,asset});await this.files.data.save();const glb=result.assets.find((a:Asset)=>a.name.endsWith('.glb'));await this.display(station,glb);status.textContent='Created Blender project, GLB display, millimetre STL and editable OpenSCAD source. They are saved in this station’s files.';await preview(glb);}catch(e){status.textContent='Build failed: '+(e as Error).message;throw e;}};
    p.body.append(h('p',{},'Turn concepts into real files. ChatGPT or Claude can choose dimensions from your prompt and concept image; the modelling tools support measured boxes, rings, vases and assemblies of boxes, cylinders, spheres and cones, with cut-outs.'),status,h('label',{},'Shape',shape),h('div.fac-grid',{},...Object.values(fields).map(f=>f.row)),h('label',{},'Material',color),h('div.fac-toolbar',{},action('Build in Blender & display prototype',build,true),action('Download editable CAD source',()=>download(station+'.scad',scad(get()))),action('Open installed Blender',()=>launch('blender')),action('Station files · upload / open / display',()=>{p.modal.close();return this.files.open(station,a=>this.display(station,a));})),h('h3',{},'Prompt & image → Blender'),prompt.row,h('label',{},'Assistant',provider),chooseFile('.png,.jpg,.jpeg,.webp',async file=>{conceptImage=await upload(file);status.textContent='Concept image selected: '+conceptImage.name;}),action('Ask assistant to design it',async()=>{status.textContent='Assistant is interpreting your concept…';const result=await post('/api/studios/concept',{provider:provider.value,prompt:prompt.field.value+'\nCurrent design to revise: '+current(),image:conceptImage?.id});put(result.recipe);status.textContent='Your assistant filled the measured design. Check the dimensions, then Build in Blender.';}),h('p.studio-help',{},`Direct API connections: OpenAI ${connections.ai.openai?'ready':'needs setup'}, Claude ${connections.ai.claude?'ready':'needs setup'}. The prompt and selected image are sent only when you press Ask assistant. Configure server API keys using the studio guide. ChatGPT/Claude website subscriptions are separate.`),h('div.fac-toolbar',{},webLink('ChatGPT','https://chatgpt.com/'),webLink('Claude','https://claude.ai/')),input('Design recipe JSON','',true).row);
    const json=p.body.querySelector<HTMLTextAreaElement>('textarea[aria-label="Design recipe JSON"]')!;p.body.append(action('Import assistant’s recipe JSON',()=>{put(recipe(JSON.parse(json.value)));status.textContent='Recipe imported. Check the measurements and build it.';}),action('Copy prompt for browser assistant',async()=>{await navigator.clipboard.writeText(prompt.field.value+'\n'+DESIGN_INSTRUCTION);toast('Prompt copied. Paste the answer into Design recipe JSON.');}));
    if(['textiles','leather'].includes(station)){const w=input('Pattern width mm','200'),hgt=input('Pattern height mm','300'),seam=input('Seam allowance mm','10');p.body.append(h('h3',{},'Measured pattern template'),w.row,hgt.row,seam.row,action('Save SVG pattern at true size',async()=>{const svg=svgPattern(Number(w.field.value),Number(hgt.field.value),Number(seam.field.value));const a=await upload(new File([svg],station+'-pattern.svg',{type:'image/svg+xml'}));await this.files.data.load();this.files.data.value.push({station,asset:a});await this.files.data.save();download(a.name,svg,'image/svg+xml');toast('Pattern saved to this station. Print at 100%.');}));}
  }
}
